import { Hook } from "@/app/types/hook";

// For MVP, hooks data is embedded directly
// In production, this could be loaded from the CLAUDE.md file or an API
export const hooksData: Hook[] = [
  {
    id: "prettier-auto-format",
    name: "Prettier Auto-Format",
    description: "Automatically formats TypeScript, JavaScript, JSON, and CSS files after every edit using Prettier. Ensures consistent code style across your project.",
    category: "code-quality",
    tags: ["formatting", "prettier", "typescript", "javascript", "css"],
    language: "javascript",
    repoUrl: "https://github.com/claudehooks/prettier-auto-format",
    author: "claudehooks",
  },
  {
    id: "dangerous-command-blocker",
    name: "Dangerous Command Blocker",
    description: "Blocks potentially dangerous bash commands like rm -rf, sudo operations, and filesystem wipes. Keeps your system safe during AI-assisted development.",
    category: "security",
    tags: ["security", "validation", "bash", "safety", "prevention"],
    language: "python",
    repoUrl: "https://github.com/security-hooks/command-blocker",
    author: "security-hooks",
  },
  {
    id: "desktop-notifier",
    name: "Desktop Notifier",
    description: "Sends desktop notifications when Claude needs your input or completes a long-running task. Works on macOS, Linux, and Windows.",
    category: "notifications",
    tags: ["notifications", "alerts", "desktop", "cross-platform", "productivity"],
    language: "bash",
    repoUrl: "https://github.com/notification-tools/claude-desktop-notifier",
    author: "notification-tools",
  },
  {
    id: "git-context-injector",
    name: "Git Context Injector",
    description: "Automatically injects git status, recent commits, and branch info at session start. Gives Claude full context of your repository state.",
    category: "context-management",
    tags: ["git", "context", "automation", "session-start", "vcs"],
    language: "bash",
    repoUrl: "https://github.com/devtools-hooks/git-context-injector",
    author: "devtools-hooks",
  },
  {
    id: "eslint-auto-fix",
    name: "ESLint Auto-Fix",
    description: "Runs ESLint with --fix flag after code edits to automatically fix linting issues. Maintains code quality standards effortlessly.",
    category: "code-quality",
    tags: ["linting", "eslint", "javascript", "typescript", "auto-fix"],
    language: "javascript",
    repoUrl: "https://github.com/linttools/eslint-claude-hook",
    author: "linttools",
  },
  {
    id: "sensitive-file-protector",
    name: "Sensitive File Protector",
    description: "Blocks edits to .env files, credentials, API keys, and other sensitive configuration files. Prevents accidental exposure of secrets.",
    category: "security",
    tags: ["security", "env-files", "credentials", "protection", "validation"],
    language: "python",
    repoUrl: "https://github.com/security-hooks/file-protector",
    author: "security-hooks",
  },
  {
    id: "black-formatter",
    name: "Black Python Formatter",
    description: "Automatically formats Python code using Black after every edit. Enforces PEP 8 style guide with zero configuration.",
    category: "code-quality",
    tags: ["formatting", "black", "python", "pep8", "style"],
    language: "python",
    repoUrl: "https://github.com/python-hooks/black-formatter",
    author: "python-hooks",
  },
  {
    id: "slack-integration",
    name: "Slack Integration",
    description: "Sends notifications to Slack channels when Claude completes tasks or needs input. Perfect for team workflows and async development.",
    category: "notifications",
    tags: ["slack", "team", "integration", "webhook", "collaboration"],
    language: "python",
    repoUrl: "https://github.com/team-hooks/claude-slack-notifier",
    author: "team-hooks",
  },
  {
    id: "auto-commit-backup",
    name: "Auto-Commit Backup",
    description: "Automatically creates git commits before compaction events. Never lose work during context compression with automatic backup commits.",
    category: "workflow",
    tags: ["git", "backup", "automation", "compaction", "safety"],
    language: "bash",
    repoUrl: "https://github.com/workflow-hooks/auto-commit-backup",
    author: "workflow-hooks",
  },
  {
    id: "test-runner",
    name: "Automatic Test Runner",
    description: "Runs your test suite after code changes to catch regressions early. Supports Jest, pytest, Go test, and other popular frameworks.",
    category: "code-quality",
    tags: ["testing", "jest", "pytest", "automation", "ci"],
    language: "javascript",
    repoUrl: "https://github.com/test-hooks/auto-test-runner",
    author: "test-hooks",
  },
  {
    id: "package-version-validator",
    name: "Package Version Validator",
    description: "Validates package.json and requirements.txt changes to prevent breaking version updates. Checks for CVEs and deprecated packages.",
    category: "security",
    tags: ["dependencies", "validation", "npm", "pip", "security"],
    language: "python",
    repoUrl: "https://github.com/security-hooks/package-validator",
    author: "security-hooks",
  },
  {
    id: "gofmt-formatter",
    name: "Go Format (gofmt)",
    description: "Automatically formats Go code using gofmt after every edit. Ensures your Go code follows official formatting standards.",
    category: "code-quality",
    tags: ["formatting", "gofmt", "go", "golang", "style"],
    language: "go",
    repoUrl: "https://github.com/go-hooks/gofmt-hook",
    author: "go-hooks",
  },
  {
    id: "docker-safety-check",
    name: "Docker Safety Check",
    description: "Validates Docker commands and Dockerfiles for security best practices. Prevents running containers with dangerous flags.",
    category: "security",
    tags: ["docker", "containers", "security", "validation", "best-practices"],
    language: "bash",
    repoUrl: "https://github.com/docker-hooks/safety-checker",
    author: "docker-hooks",
  },
  {
    id: "tts-announcer",
    name: "Text-to-Speech Announcer",
    description: "Uses text-to-speech to announce when Claude needs input or completes tasks. Great for accessibility and multitasking workflows.",
    category: "notifications",
    tags: ["tts", "accessibility", "audio", "announcements", "productivity"],
    language: "python",
    repoUrl: "https://github.com/accessibility-hooks/tts-announcer",
    author: "accessibility-hooks",
  },
  {
    id: "rustfmt-formatter",
    name: "Rust Format (rustfmt)",
    description: "Automatically formats Rust code using rustfmt after every edit. Keeps your Rust codebase clean and consistent.",
    category: "code-quality",
    tags: ["formatting", "rustfmt", "rust", "cargo", "style"],
    language: "rust",
    repoUrl: "https://github.com/rust-hooks/rustfmt-hook",
    author: "rust-hooks",
  },
  {
    id: "session-logger",
    name: "Session Logger",
    description: "Logs all Claude Code sessions to timestamped files for audit trails and debugging. Includes command history and responses.",
    category: "workflow",
    tags: ["logging", "audit", "history", "debugging", "compliance"],
    language: "bash",
    repoUrl: "https://github.com/workflow-hooks/session-logger",
    author: "workflow-hooks",
  },
  {
    id: "sql-injection-blocker",
    name: "SQL Injection Blocker",
    description: "Analyzes database queries and blocks potential SQL injection vulnerabilities. Scans for dangerous patterns in SQL strings.",
    category: "security",
    tags: ["sql", "injection", "database", "security", "validation"],
    language: "python",
    repoUrl: "https://github.com/security-hooks/sql-injection-blocker",
    author: "security-hooks",
  },
  {
    id: "jira-integration",
    name: "JIRA Task Sync",
    description: "Automatically updates JIRA tickets when Claude completes tasks. Syncs commit messages and work logs to keep project tracking up-to-date.",
    category: "workflow",
    tags: ["jira", "integration", "project-management", "automation", "api"],
    language: "python",
    repoUrl: "https://github.com/pm-hooks/jira-sync",
    author: "pm-hooks",
  },
];

export const getAllHooks = (): Hook[] => {
  return hooksData;
};
